
# Name of this set of containers
name: website

services:

  # This is the container for the Apache server
  web:
    # The location of the Dockerfile
    build:
      context: './bin/php'
      
    # A file containing sensitive information
    env_file: ".env"
      
    # The name for this container
    container_name: "server"
    
    # If anything goes wrong, restart the web server
    restart: "always"
    
    # Using both port 80 on the host and the container
    ports:
      - "80:80"
      
    volumes:
      # The 'www' directory will be mapped to the container directory "/var/www"
      - ../website/www:/var/www
      - ../website/settings.conf:/var/settings.conf
      
      # These are config files mapped to the VMs config files
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      
      # These are log directories mapped to the VMs log directories
      - ./logs/apache2:/var/log/apache2
      - ./logs/xdebug:/var/log/xdebug
      
    environment:
      # Settings for the Apache webserver
      APACHE_DOCUMENT_ROOT: /var/www
      
      # Settings for phpMyAdmin
      PMA_PORT: 8080
      
      # Settings for the MySQL database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: bible
      HOST_MACHINE_MYSQL_PORT: 3306
      
    extra_hosts:
      - "host.docker.internal:host-gateway"
    

